#              _____                ____  __
#             | ____|__ _ ___ _   _|  _ \| |_   _  __ _(_)_ __
#             |  _| / _` / __| | | | |_) | | | | |/ _` | | '_ \
#             | |__| (_| \__ \ |_| |  __/| | |_| | (_| | | | | |
#             |_____\__,_|___/\__, |_|   |_|\__,_|\__, |_|_| |_|
#             easyplugin.net  |___/               |___/
#
# GENERAL:
#
#  version: 1.0                 The version of the config (Don't change)
#
#  useStatistics: [true|false]  This sends usage Statistics to bstats.org.
#                               and helps me improving the Plugin.
#
# COMMANDS
#
# command:
#   1:              [number]         Has to be numerical, used as an iterator. No duplicates!
#     execution:    ['text']         This is the command for which you want a cooldown. No duplicates!
#     bypass:       ['text']         This is the permission to have "0" cooldown/bypass
#     cooldowns:
#       25:         [number:'text']  Number in seconds and the permission needed. You can
#       15:                          add as many as you want but each cooldown only once.
#       10:                          If there is no permission but a cooldown, the highest
#       5:                           cooldown is taken. If someone has multiple permissions
#       3:                           the lowest cooldown is taken.
#
# MESSAGES
# (Supports Colors)
#
#  plugin-prefix:        ['text']    The Prefix for messages. Leave '' if not required
#  no-permission:        ['text']    The message that appears if someone ha sno perms for /easycc reload
#  command-on-cooldown:  ['text']    The message that appears ff a command is on cooldown.
#                                    use %time% to display in seconds use %timeformatted% to display hrs,min,sec
#                                    %command% is replaced with the selected command
#
############################################################################
general:
  version: 1.0
  useStatistics: true;
command:
  1:
    execution: '/easycc'
    bypass: 'easycc.admin'
    cooldowns:
      15: 'easycc.default'
      10: 'easycc.donor'
      5: 'easycc.donor2'
      0: 'easycc.admin'
message:
  plugin_prefix: '&7[&2Easy&7CC&7] &f'
  no-permission: '&7You don''t have permission to use this command!'
  command-on-cooldown: '&7You have to wait &2%timeformatted% &7to use &2%command%&7 again'