name: EasyCommandCooldown
main: me.easyplugins.commandcooldown.EasyCommandCooldown
description: "EasyCommandCooldown enables you to set a cooldown for each and every command."
version: 1.0
author: ChanTeo